### PR TITLE
Add intial version of firewall feature

### PR DESCRIPTION
**Pull request by SISheogorath**
This patch provides an initial firewall configuration that provides
complete isolation of the cluster from the outside world. The only way
to access the cluster is through the load balancer on ports 6443 (api),
443 (https), 80 (http) and currently 22623 (ignition). Sadly, we can't
automatically apply these firewalls to hosts, since the hcloud terraform
module has a bootstrapping problem[1], so this has to be done afterwards
manually using the Webinterface or CLI. Since all instances are tagged
already, it should be trivial to apply the right firewall rules based on
the tag.

Note on 22623, exposing this port through the loadbalancer permentently
to the internet is not ideal and should be changed. However, I haven't
come up with a better solution. This will be sorted out in the long run.

[1]: https://github.com/hetznercloud/terraform-provider-hcloud/issues/336

### CODE REVIEW

**Comment by slauger** [comment]
Very Impressive, thank your for this contribution!

I'll guess the firewall rules are for the OVN SDN? Have you also tried to deploy a cluster with OpenShiftSDN? In my eyes we can drop the support for the legacy OpenShiftSDN, but then we should also a small note in the `README.md`.

I would be glad if you could share your experiences with your "okd on hcloud" deployment with us. How did your `install-config.yaml` looked like? On which region is your cluster running? Which OKD and FCOS version did you used? Count of Master/Nodes? Did you had any issues with the deployment (e.g. etcd performance issues)?

I will run a test deployment and everything works fine we can merge this.

**Comment by SISheogorath** [comment]
I have some other contributions in the pipeline, currently it's called modules, due to their loose nature to enrich okd a bit (installing cert-manager operator, install rook with hcloud-csi for encrypted storage, …) but I still haven't really settled for a format there.

The rules are currently for the default OpenShift-SDN, I didn't replace that with OVN-Kubernetes, it's planned for my next deployment, as I want to utilise encrypted networking. The rules themselves originate from the official documentation: https://docs.okd.io/latest/installing/installing_platform_agnostic/installing-platform-agnostic.html#installation-network-connectivity-user-infra_installing-platform-agnostic

And yes, I should add a small note about how to enable the firewall rules to the README. So far, I haven't actually use the rules during deployment. But as soon as the cluster is initially configured, it works fine.

> How did your install-config.yaml looked like?

Pretty much the default, 3 master nodes, no separate workers due to cost saving :D

```yaml
---
apiVersion: v1
baseDomain: 'testnet.shivering-isles.com'
metadata:
  name: 'okd4'
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
  machineCIDR:
platform:
  none: {}
pullSecret: '{"auths":{"none":{"auth": "none"}}}'
sshKey: ssh-ed25519 …
```

> On which region is your cluster running?

In was running in Nürnberg, however I looked into deploying each master node into a different region, in order to reduce possible outages. Not sure how much impact the latency will have there. Main issue were my terraform skills to make a modolo 3 operator for an array selector. If you have a hint there, more than welcome!

> Which OKD and FCOS version did you used?

Started on `4.7.0-0.okd-2021-06-19-191547` and updated seamlessly to `4.7.0-0.okd-2021-07-03-190901`. I started from `34.20210611.3.0` and the machine operator deployed `47.34.202106291017-0` as active version in rpm-ostree.

> Did you had any issues with the deployment (e.g. etcd performance issues)?

To be honest, my main issue was my skipping of steps and "knowing it better". I went for the pre-build images from quay, that ended up being working, but [only if you don't try to deploy OKD4 with the openshift-installer for OCP](https://shivering-isles.com/til/2021/07/openshift-installer-is-not-openshift-installer).

The other thing was that I tried to use smaller machines, with just 8 instead of 16GB of RAM. apparently OpenShift doesn't like that either. when they say minimal system requirements for masters are 16GB of RAM, they actually mean that.

Otherwise, no issues, neither performance-wise nor other. But I'm running a super small cluster, so etcd should be fine.

---

What also got me, was my try to move all traffic to the private network. There I learned that private networks on Hetzner don't do reverse DNS as expected and that etcd really loves PTR records. But given that all this stuff was commented out to begin with, I guess you noticed the same thing 😅

**Comment by SISheogorath** [comment]
Added the readme and added some variables I forgot to commit 😇 

Before merging, let me know, then I'll rebase everything and we get some nice history.

**Comment by slauger** [comment]
Sorry for the delay. I was quite busy in the last weeks! :(

I tested your manifests and have a running firewall in my hcloud account, but the firewall is not associated with any instance.

Bildschirmfoto 2021-08-17 um 22 32 26

I can see that you disabled the `firewall_ids` line in `main.tf`. I tried to enable the parameter, but it results in a dependency cycle.

```
│ Error: Cycle: module.worker.output.server_ids (expand), hcloud_firewall.okd-ingress, hcloud_firewall.okd-base, module.worker.var.firewall_ids (expand), module.worker.hcloud_server.server, module.worker.output.ipv4_addresses (expand), module.master.output.ipv4_addresses (expand), hcloud_firewall.okd-master, module.master.var.firewall_ids (expand), module.master.hcloud_server.server, module.master.output.server_ids (expand), hcloud_load_balancer.lb
```

Could you explain the background of this?

**Comment by SISheogorath** [comment]
Yes, that's intended, as explained in the initial commit, the reason this happens is due to how hetzner terraform handles the firewall objects. Basically in order to fill in the firewall rules, you need to know the IPs of your instances. But in order to assign firewalls to your instances, you need to know the firewall ids.

Currently there is a manual step requires, where you apply the firewalls by label to the nodes. Once the terraform provider can do "apply to label" things should also be fine.

https://github.com/hetznercloud/terraform-provider-hcloud/issues/336

That's what I did in my setup (even though, I'll provide an update to the PR, as I missed IPsec support, which I use nowadays.)

**Comment by slauger** [comment]
Ah, i see. Then i would say let's get this merged into master. A manual firewall is better than no firewall. :)

I subscribed the issue in the hcloud provider. Let's see when this get's fixed.

Maybe i will add OVN support in a seperate branch (since OVN is the prefered/default SDN for OKD4).

**Comment by slauger** [comment]
Thank you again for this great contribution!

**Pull request merged**
